"""Generate report/latex/references.bib from pipeline corpus JSON files.

For each paper in `data/processed/slr_corpus.json` (included SLRs) and
`data/processed/top_cited_techdebt.json` (top-cited corpus), fetches the
ready-made BibTeX entry from Semantic Scholar's `citationStyles` field and
emits a single `.bib` file with stable cite keys derived from the paper's
`_paper_key`.

Cite-key scheme: the paper_key (e.g. "doi:10.1109/x.2018.1") with ":" and "/"
replaced by "_" so the result is a valid BibTeX key
("doi_10.1109_x.2018.1"). Falls back to the Semantic Scholar paperId when
paper_key cannot be sanitised cleanly.

Re-uses `lib.ss_client.SSClient.get_paper` which caches under
`data/raw/ss_cache/` --- so reruns hit the cache.

Output: report/latex/references.bib (overwrites the generated block; preserves
anything below a `% MANUAL` marker line).
"""
from __future__ import annotations

import json
import logging
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from lib.config import REPO_ROOT  # noqa: E402
from lib.paperid import paper_key as compute_paper_key  # noqa: E402
from lib.ss_client import SSClient  # noqa: E402

logger = logging.getLogger(__name__)
logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")

SLR_CORPUS_PATH = REPO_ROOT / "data" / "processed" / "slr_corpus.json"
TOP_CITED_PATH = REPO_ROOT / "data" / "processed" / "top_cited_techdebt.json"
OUTPUT_PATH = REPO_ROOT / "report" / "latex" / "references.bib"

MANUAL_MARKER = "% === MANUAL ENTRIES BELOW ==="
GENERATED_HEADER = (
    "% --- AUTO-GENERATED by report/latex/build_bibtex.py ---\n"
    "% Everything above the manual-entries sentinel is overwritten on rerun.\n"
)

# BibTeX keys allow letters, digits, and a few punctuation chars. Drop the rest.
_KEY_INVALID = re.compile(r"[^A-Za-z0-9._-]")
# First line of a BibTeX entry: @type{key,
_ENTRY_FIRST_LINE = re.compile(r"^(@[A-Za-z]+\{)([^,]+)(,.*)$", re.MULTILINE)


def sanitise_key(paper_key: str | None, fallback_paper_id: str | None) -> str | None:
    """Return a valid BibTeX cite key, or None if neither source usable."""
    for raw in (paper_key, fallback_paper_id):
        if not raw:
            continue
        cleaned = _KEY_INVALID.sub("_", raw)
        if cleaned:
            return cleaned
    return None


def rewrite_first_line_key(bibtex: str, new_key: str) -> str:
    """Replace the cite key on the first `@type{...,` line of a BibTeX entry."""
    return _ENTRY_FIRST_LINE.sub(rf"\1{new_key}\3", bibtex, count=1)


_UNESCAPED_AMP = re.compile(r"(?<!\\)&")


def escape_latex_specials(bibtex: str) -> str:
    """Escape characters that BibTeX passes through to LaTeX (notably `&`).

    SS's `citationStyles.bibtex` field returns raw values like
    `journal = {Network Security & Its Applications}`, which crash pdflatex
    with "Misplaced alignment tab character &". Replace each unescaped `&`
    with `\\&`. Idempotent under repeated application.
    """
    return _UNESCAPED_AMP.sub(r"\\&", bibtex)


def fetch_bibtex(client: SSClient, paper_id: str) -> str | None:
    """Pull the SS-generated BibTeX string for a paper, or None if absent."""
    record = client.get_paper(paper_id, fields=("citationStyles",))
    styles = record.get("citationStyles") if record else None
    if not styles:
        return None
    return styles.get("bibtex")


def collect_entries(papers: list[dict], client: SSClient, source_label: str) -> list[str]:
    """Return a list of BibTeX entry strings, one per paper."""
    out: list[str] = []
    for paper in papers:
        paper_id = paper.get("paperId")
        pk = paper.get("_paper_key") or compute_paper_key(paper)
        cite_key = sanitise_key(pk, paper_id)
        if not paper_id or not cite_key:
            logger.warning("[%s] no usable SS id/key for %r; skipping", source_label, paper.get("title"))
            continue
        try:
            bibtex = fetch_bibtex(client, paper_id)
        except Exception as exc:
            logger.error("[%s] SS error fetching %s: %s", source_label, paper_id, exc)
            continue
        if not bibtex:
            logger.warning("[%s] SS returned no BibTeX for %s (%r)", source_label, paper_id, paper.get("title"))
            continue
        out.append(escape_latex_specials(rewrite_first_line_key(bibtex.strip(), cite_key)))
    return out


def _split_existing(path: Path) -> str:
    """Return the manual tail of an existing references.bib, or empty string."""
    if not path.exists():
        return ""
    text = path.read_text(encoding="utf-8")
    if MANUAL_MARKER not in text:
        return ""
    return text[text.index(MANUAL_MARKER):]


def run(
    slr_corpus_path: Path = SLR_CORPUS_PATH,
    top_cited_path: Path = TOP_CITED_PATH,
    output_path: Path = OUTPUT_PATH,
) -> int:
    if not slr_corpus_path.exists():
        raise FileNotFoundError(f"Missing {slr_corpus_path}; run merge_and_classify first.")
    if not top_cited_path.exists():
        raise FileNotFoundError(f"Missing {top_cited_path}; run fetch_top_cited first.")

    slrs = json.loads(slr_corpus_path.read_text(encoding="utf-8"))
    top_cited = json.loads(top_cited_path.read_text(encoding="utf-8"))

    client = SSClient.from_config()
    entries = collect_entries(slrs, client, "SLR corpus")
    entries += collect_entries(top_cited, client, "top-cited")

    # Dedup by cite key (an SLR can also be in the top-cited list).
    seen: set[str] = set()
    unique: list[str] = []
    for entry in entries:
        match = _ENTRY_FIRST_LINE.match(entry)
        key = match.group(2) if match else None
        if key and key in seen:
            continue
        if key:
            seen.add(key)
        unique.append(entry)

    manual_tail = _split_existing(output_path)
    body = "\n\n".join(unique) + "\n"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(GENERATED_HEADER + "\n" + body + "\n" + (manual_tail or f"{MANUAL_MARKER}\n"), encoding="utf-8")
    logger.info("Wrote %d BibTeX entries to %s", len(unique), output_path.relative_to(REPO_ROOT))
    return len(unique)


def main() -> None:
    n = run()
    print(f"references.bib: {n} entries")


if __name__ == "__main__":
    main()
